-- MySQL Script generated by MySQL Workbench
-- Fri Jan  9 14:53:32 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FormulaUno
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FormulaUno
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FormulaUno` DEFAULT CHARACTER SET utf8 ;
USE `FormulaUno` ;

-- -----------------------------------------------------
-- Table `FormulaUno`.`PAISES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FormulaUno`.`PAISES` (
  `IdPais` CHAR(3) NOT NULL,
  `NombrePais` VARCHAR(45) NOT NULL,
  `HabitantesPais` INT NOT NULL,
  PRIMARY KEY (`IdPais`),
  UNIQUE INDEX `NombrePais_UNIQUE` (`NombrePais` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FormulaUno`.`PILOTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FormulaUno`.`PILOTOS` (
  `IdPiloto` INT NOT NULL AUTO_INCREMENT,
  `NombrePiloto` VARCHAR(45) NOT NULL,
  `ApellidoPiloto` VARCHAR(45) NOT NULL,
  `PaisPiloto` CHAR(3) NOT NULL,
  PRIMARY KEY (`IdPiloto`),
  INDEX `PilotoToPais_idx` (`PaisPiloto` ASC) VISIBLE,
  CONSTRAINT `PilotoToPais`
    FOREIGN KEY (`PaisPiloto`)
    REFERENCES `FormulaUno`.`PAISES` (`IdPais`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FormulaUno`.`GPs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FormulaUno`.`GPs` (
  `IdGP` INT NOT NULL AUTO_INCREMENT,
  `DenominacionGP` VARCHAR(80) NOT NULL,
  `PaisGP` CHAR(3) NOT NULL,
  PRIMARY KEY (`IdGP`),
  INDEX `GPtoPais_idx` (`PaisGP` ASC) VISIBLE,
  CONSTRAINT `GPtoPais`
    FOREIGN KEY (`PaisGP`)
    REFERENCES `FormulaUno`.`PAISES` (`IdPais`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FormulaUno`.`ESCUDERIAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FormulaUno`.`ESCUDERIAS` (
  `IdEscuderia` INT NOT NULL AUTO_INCREMENT,
  `NombreEscuderia` VARCHAR(45) NOT NULL,
  `PaisEscuderia` CHAR(3) NOT NULL,
  `FechaCreacion` DATE NOT NULL,
  PRIMARY KEY (`IdEscuderia`),
  INDEX `EscuderiaToPais_idx` (`PaisEscuderia` ASC) VISIBLE,
  CONSTRAINT `EscuderiaToPais`
    FOREIGN KEY (`PaisEscuderia`)
    REFERENCES `FormulaUno`.`PAISES` (`IdPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FormulaUno`.`CALENDARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FormulaUno`.`CALENDARIO` (
  `Temporada` SMALLINT NOT NULL,
  `GP` INT NOT NULL,
  `Orden` TINYINT(20) NOT NULL,
  PRIMARY KEY (`Temporada`, `GP`),
  INDEX `CalendarioToGP_idx` (`GP` ASC) VISIBLE,
  CONSTRAINT `CalendarioToGP`
    FOREIGN KEY (`GP`)
    REFERENCES `FormulaUno`.`GPs` (`IdGP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FormulaUno`.`CARRERAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FormulaUno`.`CARRERAS` (
  `Temporada` SMALLINT NOT NULL,
  `GP` INT NOT NULL,
  `Piloto` INT NOT NULL,
  `Posicion` TINYINT(20) NOT NULL,
  `Puntos` TINYINT(10) NOT NULL,
  PRIMARY KEY (`Temporada`, `GP`, `Piloto`),
  INDEX `CarrerasToCalendario_idx` (`GP` ASC, `Temporada` ASC) VISIBLE,
  INDEX `CarrerasToPiloto_idx` (`Piloto` ASC) VISIBLE,
  CONSTRAINT `CarrerasToCalendario`
    FOREIGN KEY (`GP` , `Temporada`)
    REFERENCES `FormulaUno`.`CALENDARIO` (`GP` , `Temporada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CarrerasToPiloto`
    FOREIGN KEY (`Piloto`)
    REFERENCES `FormulaUno`.`PILOTOS` (`IdPiloto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FormulaUno`.`CONTRATOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FormulaUno`.`CONTRATOS` (
  `Escuderia` INT NOT NULL,
  `Temporada` SMALLINT NOT NULL,
  `Piloto1` INT NOT NULL,
  `Piloto2` INT NOT NULL,
  PRIMARY KEY (`Escuderia`, `Temporada`),
  INDEX `ContratoToPiloto1_idx` (`Piloto1` ASC) VISIBLE,
  INDEX `ContratoToPiloto2_idx` (`Piloto2` ASC) VISIBLE,
  CONSTRAINT `ContratoToEscuderia`
    FOREIGN KEY (`Escuderia`)
    REFERENCES `FormulaUno`.`ESCUDERIAS` (`IdEscuderia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ContratoToPiloto1`
    FOREIGN KEY (`Piloto1`)
    REFERENCES `FormulaUno`.`PILOTOS` (`IdPiloto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ContratoToPiloto2`
    FOREIGN KEY (`Piloto2`)
    REFERENCES `FormulaUno`.`PILOTOS` (`IdPiloto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `FormulaUno`;

DELIMITER $$
USE `FormulaUno`$$
CREATE DEFINER = CURRENT_USER TRIGGER `FormulaUno`.`CONTRATOS_BEFORE_INSERT` BEFORE INSERT ON `CONTRATOS` FOR EACH ROW
BEGIN
	if new.piloto1=new.piloto2 then
		signal SQLSTATE '45000' set message_text='Los pilotos de una escudería no pueden repetirse en una misma temporada';
    end if;    
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
